workflows:
  version: 2
  php-multi-build:
    jobs:
      # - php-7.2

version: 2
jobs:
  php-base: &php-base
    working_directory: ~/code
    docker:
      - image: rmts/app
    steps:
      - checkout
      - run:
         name: Setup Laravel testing environment variables for CircleCI tests
         command: cp .circleci/.env.testing .env

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}

      - run: composer install -n --prefer-dist --no-interaction
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
         name: Generate application key
         command: php artisan key:generate

      - run:
         name: Flush config cache
         command: php artisan config:cache

      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true

      - run:
         name: Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing
         command: vendor/bin/phpunit -c ./.circleci/phpunit.xml

  php-7.2:
    <<: *php-base
    docker:
      - image: rmts/app:7.2-ubuntu18
